"""add comments table

Revision ID: 06715cca3725
Revises: 7e45c6045306
Create Date: 2023-07-28 15:01:12.962832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06715cca3725'
down_revision = '7e45c6045306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('shanyrak_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'shanyraks', ['shanyrak_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'shanyrak_id')
    # ### end Alembic commands ###
